In [19]:
import pandas as pd

df = pd.read_csv('../data/data_prep/2019-22_draft.csv')

In [20]:
print(df.describe())
df

        Player   Pos   School        College    Ht    Wt  40yd Vertical Bench  \
count     1127  1127     1127           1080  1098  1103   900      872   629
unique    1123    22      177              2    18   170   133       51    36
top     Player    WR  Georgia  College Stats   6-4   197  4.48     34.5    21
freq         2   158       36           1078   142    22    25       50    43

       Broad Jump 3Cone Shuttle  Drafted (tm/rnd/yr) Player-additional
count         841   598     620                  648              1127
unique         48   157     117                  647               948
top           123  7.00    4.28  Drafted (tm/rnd/yr)             -9999
freq           51    17      19                    2               179

,Player,Pos,School,College,Ht,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle,Drafted (tm/rnd/yr),Player-additional
0,Trey Adams,OL,Washington,College Stats,6-8,318,5.60,24.5,NaN,92,NaN,NaN,NaN,AdamTr01
1,Hakeem Adeniji,OL,Kansas,College Stats,6-4,302,5.17,34.0,26,115,NaN,NaN,Cincinnati Bengals / 6th / 180th pick / 2020,AdenHa00
2,McTelvin Agim,DL,Arkansas,College Stats,6-3,309,4.98,NaN,27,NaN,NaN,NaN,Denver Broncos / 3rd / 95th pick / 2020,AgimMc00
3,Salvon Ahmed,RB,Washington,College Stats,5-11,197,4.62,34.5,NaN,120,NaN,NaN,NaN,AhmeSa01
4,Brandon Aiyuk,WR,Arizona State,College Stats,6-0,205,4.50,40.0,11,128,NaN,NaN,San Francisco 49ers / 1st / 25th pick / 2020,AiyuBr00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1122,Devonte Wyatt,DT,Georgia,College Stats,6-3,304,4.77,29.0,NaN,111,NaN,NaN,Green Bay Packers / 1st / 28th pick / 2022,WyatDe00
1123,Jalen Wydermyer,TE,Texas A&M,College Stats,6-4,255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WydeJa00
1124,Cade York,K,LSU,College Stats,6-1,206,NaN,NaN,12,NaN,NaN,NaN,Cleveland Browns / 4th / 124th pick / 2022,YorkCa00
1125,Nick Zakelj,OT,Fordham,NaN,6-6,316,5.13,28.5,27,110,7.75,4.71,San Francisco 49ers / 6th / 187th pick / 2022,ZakeNi00
1126,Bailey Zappe,QB,Western Kentucky,College Stats,6-1,215,4.88,30.0,NaN,109,7.19,4.40,New England Patriots / 4th / 137th pick / 2022,ZappBa00

In [21]:
df = df.rename(columns={"Drafted (tm/rnd/yr)": "Drafted"})

In [22]:
df.columns = [col.lower() for col in df.columns]
df.head()

,player,pos,school,college,ht,wt,40yd,vertical,bench,broad jump,3cone,shuttle,drafted,player-additional
0,Trey Adams,OL,Washington,College Stats,6-8,318,5.60,24.5,NaN,92,NaN,NaN,NaN,AdamTr01
1,Hakeem Adeniji,OL,Kansas,College Stats,6-4,302,5.17,34.0,26,115,NaN,NaN,Cincinnati Bengals / 6th / 180th pick / 2020,AdenHa00
2,McTelvin Agim,DL,Arkansas,College Stats,6-3,309,4.98,NaN,27,NaN,NaN,NaN,Denver Broncos / 3rd / 95th pick / 2020,AgimMc00
3,Salvon Ahmed,RB,Washington,College Stats,5-11,197,4.62,34.5,NaN,120,NaN,NaN,NaN,AhmeSa01
4,Brandon Aiyuk,WR,Arizona State,College Stats,6-0,205,4.50,40.0,11,128,NaN,NaN,San Francisco 49ers / 1st / 25th pick / 2020,AiyuBr00

In [23]:
def parse_height(height_str):
    if pd.isna(height_str) or height_str == 'Ht':
        return None
    try:
        feet, inches = map(int, height_str.split("-"))
        return feet + inches / 12.0
    except:
        return None

df["ht_num"] = df["ht"].apply(parse_height)

In [24]:
df["round"] = df["drafted"].str.extract("/ (\d+)", expand=False)

In [25]:
draft = df.dropna(subset='drafted')
draft

,player,pos,school,college,ht,wt,40yd,vertical,bench,broad jump,3cone,shuttle,drafted,player-additional,ht_num,round
1,Hakeem Adeniji,OL,Kansas,College Stats,6-4,302,5.17,34.0,26,115,NaN,NaN,Cincinnati Bengals / 6th / 180th pick / 2020,AdenHa00,6.333333,6
2,McTelvin Agim,DL,Arkansas,College Stats,6-3,309,4.98,NaN,27,NaN,NaN,NaN,Denver Broncos / 3rd / 95th pick / 2020,AgimMc00,6.250000,3
4,Brandon Aiyuk,WR,Arizona State,College Stats,6-0,205,4.50,40.0,11,128,NaN,NaN,San Francisco 49ers / 1st / 25th pick / 2020,AiyuBr00,6.000000,1
5,Cam Akers,RB,Florida State,College Stats,5-10,217,4.47,35.5,20,122,NaN,4.42,Los Angeles Rams / 2nd / 52nd pick / 2020,AkerCa00,5.833333,2
6,Bradlee Anae,DL,Utah,College Stats,6-3,257,4.93,31.0,25,115,7.44,4.43,Dallas Cowboys / 5th / 179th pick / 2020,AnaeBr00,6.250000,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,Alex Wright,DE,Alabama-Birmingham,College Stats,6-5,271,NaN,NaN,15,NaN,NaN,NaN,Cleveland Browns / 3rd / 78th pick / 2022,WrigAl01,6.416667,3
1122,Devonte Wyatt,DT,Georgia,College Stats,6-3,304,4.77,29.0,NaN,111,NaN,NaN,Green Bay Packers / 1st / 28th pick / 2022,WyatDe00,6.250000,1
1124,Cade York,K,LSU,College Stats,6-1,206,NaN,NaN,12,NaN,NaN,NaN,Cleveland Browns / 4th / 124th pick / 2022,YorkCa00,6.083333,4
1125,Nick Zakelj,OT,Fordham,NaN,6-6,316,5.13,28.5,27,110,7.75,4.71,San Francisco 49ers / 6th / 187th pick / 2022,ZakeNi00,6.500000,6
1126,Bailey Zappe,QB,Western Kentucky,College Stats,6-1,215,4.88,30.0,NaN,109,7.19,4.40,New England Patriots / 4th / 137th pick / 2022,ZappBa00,6.083333,4

In [26]:
draft = draft.drop(columns=['drafted','player-additional','college','ht'], axis=1)
draft

,player,pos,school,wt,40yd,vertical,bench,broad jump,3cone,shuttle,ht_num,round
1,Hakeem Adeniji,OL,Kansas,302,5.17,34.0,26,115,NaN,NaN,6.333333,6
2,McTelvin Agim,DL,Arkansas,309,4.98,NaN,27,NaN,NaN,NaN,6.250000,3
4,Brandon Aiyuk,WR,Arizona State,205,4.50,40.0,11,128,NaN,NaN,6.000000,1
5,Cam Akers,RB,Florida State,217,4.47,35.5,20,122,NaN,4.42,5.833333,2
6,Bradlee Anae,DL,Utah,257,4.93,31.0,25,115,7.44,4.43,6.250000,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1120,Alex Wright,DE,Alabama-Birmingham,271,NaN,NaN,15,NaN,NaN,NaN,6.416667,3
1122,Devonte Wyatt,DT,Georgia,304,4.77,29.0,NaN,111,NaN,NaN,6.250000,1
1124,Cade York,K,LSU,206,NaN,NaN,12,NaN,NaN,NaN,6.083333,4
1125,Nick Zakelj,OT,Fordham,316,5.13,28.5,27,110,7.75,4.71,6.500000,6
1126,Bailey Zappe,QB,Western Kentucky,215,4.88,30.0,NaN,109,7.19,4.40,6.083333,4

In [27]:
draft.to_csv(
    "2019-22_drafted.csv",
    index=False,
    header=True,
    sep=",",
    na_rep="NA",
    quotechar='"',
    encoding="utf-8",
)

In [14]:
df_av = pd.read_csv(
    "../data/data_prep/2019-22_av.csv"
)
df_av.head()

   Year          Player  Career AV
0  2020      Trey Adams          0
1  2020  Hakeem Adeniji          0
2  2020   McTelvin Agim          2
3  2020    Salvon Ahmed          0
4  2020   Brandon Aiyuk         39

In [15]:
df_av.columns = [col.lower() for col in df_av.columns]

In [16]:
full_df = draft.merge(df_av, on='player', how='left')
full_df.head()

,player,pos,school,wt,40yd,vertical,bench,broad jump,3cone,shuttle,ht_num,round,year,career av
0,Hakeem Adeniji,OL,Kansas,302,5.17,34.0,26,115,NaN,NaN,6.333333,6,2020.0,0.0
1,McTelvin Agim,DL,Arkansas,309,4.98,NaN,27,NaN,NaN,NaN,6.250000,3,2020.0,2.0
2,Brandon Aiyuk,WR,Arizona State,205,4.50,40.0,11,128,NaN,NaN,6.000000,1,2020.0,39.0
3,Cam Akers,RB,Florida State,217,4.47,35.5,20,122,NaN,4.42,5.833333,2,2020.0,13.0
4,Bradlee Anae,DL,Utah,257,4.93,31.0,25,115,7.44,4.43,6.250000,5,2020.0,0.0

In [17]:
full_df.count()

player        704
pos           704
school        704
wt            690
40yd          559
vertical      538
bench         355
broad jump    515
3cone         323
shuttle       339
ht_num        687
round         702
year          652
career av     652
dtype: int64

In [18]:
full_df.drop_duplicates('player')

,player,pos,school,wt,40yd,vertical,bench,broad jump,3cone,shuttle,ht_num,round,year,career av
0,Hakeem Adeniji,OL,Kansas,302,5.17,34.0,26,115,NaN,NaN,6.333333,6,2020.0,0.0
1,McTelvin Agim,DL,Arkansas,309,4.98,NaN,27,NaN,NaN,NaN,6.250000,3,2020.0,2.0
2,Brandon Aiyuk,WR,Arizona State,205,4.50,40.0,11,128,NaN,NaN,6.000000,1,2020.0,39.0
3,Cam Akers,RB,Florida State,217,4.47,35.5,20,122,NaN,4.42,5.833333,2,2020.0,13.0
4,Bradlee Anae,DL,Utah,257,4.93,31.0,25,115,7.44,4.43,6.250000,5,2020.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,Alex Wright,DE,Alabama-Birmingham,271,NaN,NaN,15,NaN,NaN,NaN,6.416667,3,2021.0,6.0
696,Devonte Wyatt,DT,Georgia,304,4.77,29.0,NaN,111,NaN,NaN,6.250000,1,2021.0,6.0
698,Cade York,K,LSU,206,NaN,NaN,12,NaN,NaN,NaN,6.083333,4,2021.0,1.0
700,Nick Zakelj,OT,Fordham,316,5.13,28.5,27,110,7.75,4.71,6.500000,6,2021.0,0.0
702,Bailey Zappe,QB,Western Kentucky,215,4.88,30.0,NaN,109,7.19,4.40,6.083333,4,2021.0,2.0

In [ ]:
full_df.to_csv(
    "2019-22_drafted-av.csv",
    index=False,
    header=True,
    sep=",",
    na_rep="NA",
    quotechar='"',
    encoding="utf-8",
)